apiVersion: observability.merlionos.org/v1
kind: PrometheusCluster
metadata:
  labels:
    app.kubernetes.io/name: tsdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo
spec:
  replicas: 1
  image: prom/prometheus:v2.55.1
  retention: 15d
  storage:
    size: 1Gi
